## 11

[분개장_1급_09회_1.csv](https://grepp-monito.s3.amazonaws.com/production/file_resource/2432/%EB%B6%84%EA%B0%9C%EC%9E%A5_1%EA%B8%89_09%ED%9A%8C_1.csv)
에서 대변(H)금액의 합계가 가장 큰 계정코드를 숫자만 입력하기 (5점)

정답: 90003

### ① 데이터불러오기

In [5]:
from pathlib import Path
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

DATASET_DIR = Path("../../assets/sources/datasets/exam_sample_data")

df = pd.read_csv(DATASET_DIR / "분개장_1급_09회_1.csv")
df.head()

       전표일자  전표번호      증빙일자  전표라인번호 차대변지시자  현지통화금액   계정코드     계정과목  거래처코드
0  20100101   304  20100101       1      H    8000  20013   미지급금_3  emp01
1  20100101   304  20100101       2      S    7272  60025  복리후생비_8  emp01
2  20100101   304  20100101       3      S     728  10100    선급부가세  emp01
3  20100101  4827  20100101       1      H   15000  20013   미지급금_3  emp05
4  20100101  4827  20100101       2      S   13636  60023  복리후생비_6  emp05

### ② 차변 대변 금액 나누어 표시

In [32]:
import numpy as np

df["차변금액"] = np.where(df["차대변지시자"].eq("S"), df["현지통화금액"], 0)
df["대변금액"] = np.where(df["차대변지시자"].eq("H"), df["현지통화금액"], 0)

df.head()

       전표일자  전표번호      증빙일자  전표라인번호 차대변지시자  현지통화금액   계정코드     계정과목  거래처코드   차변금액   대변금액
0  20100101   304  20100101       1      H    8000  20013   미지급금_3  emp01      0   8000
1  20100101   304  20100101       2      S    7272  60025  복리후생비_8  emp01   7272      0
2  20100101   304  20100101       3      S     728  10100    선급부가세  emp01    728      0
3  20100101  4827  20100101       1      H   15000  20013   미지급금_3  emp05      0  15000
4  20100101  4827  20100101       2      S   13636  60023  복리후생비_6  emp05  13636      0

### ③ 계정코드로 groupby 하여 정렬

In [37]:
summary = (
    df.groupby(["계정코드", "계정과목"])
      .agg(
          차변금액합계=("차변금액", "sum"),
          대변금액합계=("대변금액", "sum"),
      )
      .reset_index()
)

display(summary.sort_values(by="대변금액합계", ascending=False))

      계정코드        계정과목       차변금액합계       대변금액합계
199  90003        CL_3  13042642810  26963974942
197  90001        CL_1   1337895460   4035048186
4    10009      보통예금_1            0   2534514082
47   10101          제품   2249712408   2236632780
48   10102         반제품   2913363744   2195787586
..     ...         ...          ...          ...
145  60047  감가상각비_공구기구       161954            0
144  60042     지급임차료_2      2179820            0
143  60038     세금과공과_6       155180            0
142  60036     세금과공과_4      3112800            0
107  40042       차이_26        19510            0

[214 rows x 4 columns]