## 13

[분개장_1급_09회_1.csv](https://grepp-monito.s3.amazonaws.com/production/file_resource/2432/%EB%B6%84%EA%B0%9C%EC%9E%A5_1%EA%B8%89_09%ED%9A%8C_1.csv)
에서 정상매출거래가 아닌 전표세트의 개수를 숫자로만 나타내라. 단, 천단위 콤마는 나타내지 않는다. (7점)

정답: 216

> **정상매출전표세트조건** <br>
> - 간주계정과목 == "매출" & ( 차변금액 < 0 | 대변금액 > 0) 인 라인을 포함하면서 동시에 <br>
> - 간주계정과목 == "매출상대" & ( 차변금액 > 0 | 대변금액 < 0) 인 라인도 포함

> **비정상매출전표세트조건** <br>
> - 간주계정과목 == "매출" & ( 차변금액 < 0 | 대변금액 > 0) 인 라인을 포함하면서 동시에 <br>
> - 간주계정과목 == "매출상대" & ( 차변금액 > 0 | 대변금액 < 0) 인 라인은 하나라도 존재하면 안됨


| 계정코드 | 계정과목       | 간주계정과목         |
|----------|---------------|----------------------|
| 10003    | 당좌예금_1    | 매출상대            |
| 10004    | 당좌예금_2    | 매출상대            |
| 10005    | 당좌예금_3    | 매출상대            |
| 10006    | 당좌예금_4    | 매출상대            |
| 10009    | 보통예금_1    | 매출상대            |
| 10011    | 보통예금_3    | 매출상대            |
| 10012    | 보통예금_4    | 매출상대            |
| 10013    | 보통예금_5    | 매출상대            |
| 10015    | 보통예금_7    | 매출상대            |
| 10018    | 보통예금_10   | 매출상대            |
| 10022    | 보통예금_14   | 매출상대            |
| 10026    | 보통예금_18   | 매출상대            |
| 10028    | 보통예금_20   | 매출상대            |
| 10036    | 보통예금_28   | 매출상대            |
| 10038    | 보통예금_30   | 매출상대            |
| 10040    | 보통예금_32   | 매출상대            |
| 10048    | 보통예금_40   | 매출상대            |
| 10053    | 보통예금_45   | 매출상대            |
| 10055    | 보통예금_47   | 매출상대            |
| 10059    | 보통예금_51   | 매출상대            |
| 10061    | 보통예금_53   | 매출상대            |
| 10064    | 보통예금_56   | 매출상대            |
| 10066    | 보통예금_58   | 매출상대            |
| 10080    | 외상매출금_1  | 매출상대            |
| 10086    | 받을어음_1    | 매출상대            |
| 10092    | 미수금_1      | 매출상대            |
| 40001    | 제품매출액_1  | 매출                |
| 40002    | 제품매출액_2  | 매출                |
| 40004    | 상품매출액_1  | 매출                |
| 40005    | 상품매출액_2  | 매출                |
| 40007    | 반제품매출액_1| 매출                |
| 40009    | 부산물매출액_1| 매출                |
| 40011    | 부재료매출액_1| 매출                |
| 40013    | 용역매출액_1  | 매출                |
| 10017    | 보통예금_9    | 매출상대            |
| 10021    | 보통예금_13   | 매출상대            |
| 10023    | 보통예금_15   | 매출상대            |
| 10027    | 보통예금_19   | 매출상대            |
| 10032    | 보통예금_24   | 매출상대            |
| 10037    | 보통예금_29   | 매출상대            |
| 10039    | 보통예금_31   | 매출상대            |
| 10044    | 보통예금_36   | 매출상대            |
| 10050    | 보통예금_42   | 매출상대            |
| 10054    | 보통예금_46   | 매출상대            |
| 10057    | 보통예금_49   | 매출상대            |
| 10060    | 보통예금_52   | 매출상대            |
| 10063    | 보통예금_55   | 매출상대            |
| 10065    | 보통예금_57   | 매출상대            |
| 10067    | 보통예금_59   | 매출상대            |
| 10084    | 외상매출금_5  | 매출상대            |
| 10087    | 받을어음_2    | 매출상대            |
| 20017    | 선수금_1      | 매출상대            |


정답: 11

### ① 데이터불러오기

In [40]:
from pathlib import Path
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

DATASET_DIR = Path("../../assets/sources/datasets/exam_sample_data")

df = pd.read_csv(DATASET_DIR / "분개장_1급_09회_1.csv")
df.head()

       전표일자  전표번호      증빙일자  전표라인번호 차대변지시자  현지통화금액   계정코드     계정과목  거래처코드
0  20100101   304  20100101       1      H    8000  20013   미지급금_3  emp01
1  20100101   304  20100101       2      S    7272  60025  복리후생비_8  emp01
2  20100101   304  20100101       3      S     728  10100    선급부가세  emp01
3  20100101  4827  20100101       1      H   15000  20013   미지급금_3  emp05
4  20100101  4827  20100101       2      S   13636  60023  복리후생비_6  emp05

### ② 차변 대변 금액 나누어 표시

In [41]:
import numpy as np

df["차변금액"] = np.where(df["차대변지시자"].eq("S"), df["현지통화금액"], 0)
df["대변금액"] = np.where(df["차대변지시자"].eq("H"), df["현지통화금액"], 0)

df.head()

       전표일자  전표번호      증빙일자  전표라인번호 차대변지시자  현지통화금액   계정코드     계정과목  거래처코드   차변금액   대변금액
0  20100101   304  20100101       1      H    8000  20013   미지급금_3  emp01      0   8000
1  20100101   304  20100101       2      S    7272  60025  복리후생비_8  emp01   7272      0
2  20100101   304  20100101       3      S     728  10100    선급부가세  emp01    728      0
3  20100101  4827  20100101       1      H   15000  20013   미지급금_3  emp05      0  15000
4  20100101  4827  20100101       2      S   13636  60023  복리후생비_6  emp05  13636      0

### ③ 라인별 정상매출 요건 칼럼 정의

In [42]:
REVENUE_ACCT_CODES = {40001, 40002, 40004, 40005, 40007, 40009, 40011, 40013}
REVENUE_COUNTERPART_ACCT_CODES = {10003,10004,10005,10006,10009,10011,10012, 10013,10015,10017,10018,10021,10022,10023,10026,10027,10028,10032,10036,10037,10038,10039,10040,10044,10048,10050,10053,10054,10055,10057,10059,10060,10061,10063,10064,10065,10066,10067,10080,10084,10086,10087,10092,20017}

is_revenue_normal = (
    df["계정코드"].isin(REVENUE_ACCT_CODES)
    & ((df["차변금액"] < 0) | (df["대변금액"] > 0))
    )

is_counterpart_normal = (
    df["계정코드"].isin(REVENUE_COUNTERPART_ACCT_CODES)
    & ((df["차변금액"] > 0) | (df["대변금액"] < 0))
    )


df["REVENUE_FLAG"] = is_revenue_normal.astype("int")
df["COUNTERPART_FLAG"] = is_counterpart_normal.astype("int")


df.head()

       전표일자  전표번호      증빙일자  전표라인번호 차대변지시자  현지통화금액   계정코드     계정과목  거래처코드   차변금액   대변금액  REVENUE_FLAG  COUNTERPART_FLAG
0  20100101   304  20100101       1      H    8000  20013   미지급금_3  emp01      0   8000             0                 0
1  20100101   304  20100101       2      S    7272  60025  복리후생비_8  emp01   7272      0             0                 0
2  20100101   304  20100101       3      S     728  10100    선급부가세  emp01    728      0             0                 0
3  20100101  4827  20100101       1      H   15000  20013   미지급금_3  emp05      0  15000             0                 0
4  20100101  4827  20100101       2      S   13636  60023  복리후생비_6  emp05  13636      0             0                 0

### ④ 전표세트PK로 groupby 후 전표세트별 요건판단

In [43]:
voucher_summary = (
    df.groupby(["전표일자", "전표번호"])
        .agg(
            REVENUE_FLAG_SUM=("REVENUE_FLAG", "sum"),
            COUNTERPART_FLAG_SUM=("COUNTERPART_FLAG", "sum"),
        )
        .reset_index()
)

voucher_summary.head()

       전표일자    전표번호  REVENUE_FLAG_SUM  COUNTERPART_FLAG_SUM
0  20100101     304                 0                     0
1  20100101    4827                 0                     0
2  20100101  145106                 0                     1
3  20100101  243010                 0                     0
4  20100101  243171                 0                     0

### ⑤ 비정상거래 출력

In [44]:
abnormal_vouchers = voucher_summary[
    (voucher_summary["REVENUE_FLAG_SUM"] > 0) &
    (voucher_summary["COUNTERPART_FLAG_SUM"] == 0)
]

len(abnormal_vouchers)

216