## 12

[분개장_1급_09회_1.csv](https://grepp-monito.s3.amazonaws.com/production/file_resource/2432/%EB%B6%84%EA%B0%9C%EC%9E%A5_1%EA%B8%89_09%ED%9A%8C_1.csv)
에서 제품매출액_1(계정코드 40001)의 대변금액 합계가 가장 큰 월(month)의 숫자를 입력하라 (5점)

정답: 11

### ① 데이터불러오기

In [7]:
from pathlib import Path
import pandas as pd

pd.set_option('display.max_columns', None)
pd.set_option('display.width', 1000)

DATASET_DIR = Path("../../assets/sources/datasets/exam_sample_data")

df = pd.read_csv(DATASET_DIR / "분개장_1급_09회_1.csv")
df.head()

       전표일자  전표번호      증빙일자  전표라인번호 차대변지시자  현지통화금액   계정코드     계정과목  거래처코드
0  20100101   304  20100101       1      H    8000  20013   미지급금_3  emp01
1  20100101   304  20100101       2      S    7272  60025  복리후생비_8  emp01
2  20100101   304  20100101       3      S     728  10100    선급부가세  emp01
3  20100101  4827  20100101       1      H   15000  20013   미지급금_3  emp05
4  20100101  4827  20100101       2      S   13636  60023  복리후생비_6  emp05

### ② 차변 대변 금액 나누어 표시

In [8]:
import numpy as np

df["차변금액"] = np.where(df["차대변지시자"].eq("S"), df["현지통화금액"], 0)
df["대변금액"] = np.where(df["차대변지시자"].eq("H"), df["현지통화금액"], 0)

df.head()

       전표일자  전표번호      증빙일자  전표라인번호 차대변지시자  현지통화금액   계정코드     계정과목  거래처코드   차변금액   대변금액
0  20100101   304  20100101       1      H    8000  20013   미지급금_3  emp01      0   8000
1  20100101   304  20100101       2      S    7272  60025  복리후생비_8  emp01   7272      0
2  20100101   304  20100101       3      S     728  10100    선급부가세  emp01    728      0
3  20100101  4827  20100101       1      H   15000  20013   미지급금_3  emp05      0  15000
4  20100101  4827  20100101       2      S   13636  60023  복리후생비_6  emp05  13636      0

### ③ 월 데이터 생성

In [21]:
df["월"] = pd.to_datetime(df["전표일자"], format="%Y%m%d").dt.month

df.head()

       전표일자  전표번호      증빙일자  전표라인번호 차대변지시자  현지통화금액   계정코드     계정과목  거래처코드   차변금액   대변금액  월
0  20100101   304  20100101       1      H    8000  20013   미지급금_3  emp01      0   8000  1
1  20100101   304  20100101       2      S    7272  60025  복리후생비_8  emp01   7272      0  1
2  20100101   304  20100101       3      S     728  10100    선급부가세  emp01    728      0  1
3  20100101  4827  20100101       1      H   15000  20013   미지급금_3  emp05      0  15000  1
4  20100101  4827  20100101       2      S   13636  60023  복리후생비_6  emp05  13636      0  1

### ④ 계정코드 필터링

In [22]:
df_filtered = df[df["계정코드"].eq(40001)]

df_filtered.head()

         전표일자    전표번호      증빙일자  전표라인번호 차대변지시자   현지통화금액   계정코드     계정과목  거래처코드  차변금액     대변금액  월
565  20100102  184197  20100102       2      H  2211600  40001  제품매출액_1  emp17     0  2211600  1
567  20100102  184197  20100102       4      H  1668400  40001  제품매출액_1  emp17     0  1668400  1
569  20100102  185116  20100102       2      H  3801416  40001  제품매출액_1  emp21     0  3801416  1
678  20100103  187442  20100103       3      H  1562400  40001  제품매출액_1  emp08     0  1562400  1
720  20100104  185079  20100104       2      H   840000  40001  제품매출액_1  emp17     0   840000  1

### ⑤ 월로 groupby 하여 정렬

In [ ]:
summary = (
    df_filtered.groupby(["월"])
      .agg(
          차변금액합계=("차변금액", "sum"),
          대변금액합계=("대변금액", "sum"),
      )
      .reset_index()
)

display(summary.sort_values(by="대변금액합계", ascending=False))

     월    차변금액합계     대변금액합계
10  11         0  225144544
5    6     42700  171450734
2    3         0  169477514
0    1  13797080  157558520
1    2   1380000  147255602
7    8        10  128566900
3    4    546000  126740582
6    7  13530360  111688668
11  12         0  108982110
9   10         0   86927940
4    5         0   85485142
8    9         0   60146230